### ISSUE TITLE
Waila integration SMP

### ISSUE THREAD

**Issue by Keridos** [TeamWhammich/Soul-Shards-The-Old-Ways#41]
For me on latest curseforge release (0.1-RC9)  the Waila Integration is broken in SMP. The spawners should show their content but they do not show it in the waila tooltip.

**Comment by SgtPunishment** [comment]
This is a known issue, due to internal restructuring we forgot to update where the waila provider the located, it's fixed in the next release (should be dropping any day now)

On 29 April 2015, at 00:46, Keridos <notifications@github.com> wrote:

For me on latest curseforge release (0.1-RC9) the Waila Integration is broken in SMP. The spawners should show their content but they do not show it in the waila tooltip.
